expense_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("", include("django.contrib.auth.urls")),
]

main/urls.py
from django.urls import path
from .views import (
    SignUpView, 
    DashboardView, 
    LoginView, 
    ExpenseCategoryView, 
    LogoutView, 
    AccountView,
    HomeView
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    #path("privacy", PrivacyPolicyView.as_view(), name="privacy"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("login/", LoginView.as_view(redirect_authenticated_user=True), name="login"),
    path("account/", AccountView.as_view(), name="account"),
    path("<slug:slug>/", ExpenseCategoryView.as_view(), name="expense_category"),
]

main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import datetime
from django.core.validators import validate_email


class User(AbstractUser):
    email = models.EmailField(unique=True, validators=[validate_email])


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=255, verbose_name='Name')
    long_description = models.TextField(verbose_name='Description')
    slug = models.CharField(max_length=255, verbose_name='Slug')
    hex_color = models.CharField(max_length=255, verbose_name='Hex Color')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Expense(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(ExpenseCategory, on_delete=models.CASCADE)
    date = models.DateField(default=datetime.date.today, verbose_name='Date')
    amount = models.FloatField(default=0, verbose_name='Amount')
    description = models.CharField(max_length=255, verbose_name='Description')

    class Meta:
        ordering = ['date']

    def __str__(self):
        return self.description

main/forms.py
import re
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import (
    User, 
    Expense, 
    ExpenseCategory
)


class CustomModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Loop through the fields and set their labels to the verbose_name of the model field
        # keep the label setting / verbose_name in one place (model), be able to override fields
        # in form classes here and not need to set the label again
        for field_name, field in self.fields.items():
            model_field = self._meta.model._meta.get_field(field_name)
            if model_field.verbose_name:
                field.label = model_field.verbose_name


class ExpenseCategoryForm(CustomModelForm):
    hex_color = forms.CharField(
        max_length=7,
        help_text='For use with chart rendering',
        widget=forms.TextInput(attrs={'type': 'color'})
    )
    
    class Meta:
        model = ExpenseCategory
        fields = ['name', 'long_description', 'slug', 'hex_color']


class ExpenseForm(CustomModelForm):
    
    class Meta:
        model = Expense
        fields = ['amount', 'description']


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        max_length=100, 
        help_text='Required. Only alphanumeric characters allowed.'
    )
    email = forms.EmailField(
        max_length=254, 
        help_text='Required. A valid email address.'
    )
    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text='Required. Choose a secure password.',
    )
    password2 = forms.CharField(
        label='Password confirmation',
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        help_text='Required. Verify your password.',
    )

    def clean(self):
        cleaned_data = super(SignUpForm, self).clean()
        username = cleaned_data.get('username')
        if not re.match("^[A-Za-z0-9]+$", username):
            self.add_error('username', 'Only alphanumeric characters allowed in username.')
        return cleaned_data


    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

main/views.py
from datetime import datetime
import json
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.signals import user_logged_out, user_login_failed
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views import generic, View
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import Sum
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.views.generic.detail import DetailView

from .forms import (
    SignUpForm, 
    ExpenseForm
)
from .models import (
    Expense, 
    ExpenseCategory
)


def logout_message(sender, user, request, **kwargs):
    messages.success(request, '<i class="bi bi-check-circle-fill"></i> You have been successfully logged out.')

def login_failed_message(sender, credentials, request, **kwargs):
    messages.error(request, '<i class="bi bi-x-circle-fill"></i> Login failed.')

user_logged_out.connect(logout_message)
user_login_failed.connect(login_failed_message)


class LoggedInView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('login')
    template_name = None


class LoggedInDetailView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('login')
    template_name = None


class HomeView(View):
    def get(self, request, *args, **kwargs):
        return redirect('login')


class LoginView(auth_views.LoginView):
    form_class = AuthenticationForm
    template_name = "main/login.html"


class LogoutView(View):

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('login')


class SignUpView(SuccessMessageMixin, generic.CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy("login")
    template_name = "main/signup.html"
    success_message = '<i class="bi bi-check-circle-fill"></i> Signup complete. You may now log in.'

    def get(self, request, *args, **kwargs):
        self.object = None
        if request.user.is_authenticated:
            return redirect('dashboard')
        return super().get(request, *args, **kwargs)
    

class AccountView(LoggedInView):
    template_name = "main/account.html"

    def post(self, request, *args, **kwargs):
        submit_val = request.POST.get('submit')

        if submit_val == 'changeemail':
            new_email = request.POST.get('new_email')

            try:
                request.user.email = new_email
                request.user.clean_fields()
                request.user.save()
            except ValidationError:
                messages.error(request, 'Invalid email address.')
            except IntegrityError:
                messages.error(request, 'Email address change failed.')
            else:
                messages.success(request, 'Your email address has been changed.')

        if submit_val == 'deleteaccount':
            if request.user.is_staff:
                messages.error(request, 'Staff / Admin accounts cannot be deleted.')
            else:
                request.user.delete()
                return redirect('home')

        return HttpResponseRedirect(self.request.path_info)
    
    def get(self, request, *args, **kwargs):

        data = {
            'user_email': request.user.email
        }

        return render(request, self.template_name, data)


class DashboardView(LoggedInView):
    template_name = "main/dashboard.html"
    expense_model = Expense

    def get(self, request, *args, **kwargs):

        this_month = datetime.now().month
        this_year = datetime.now().year

        amount_sum = 0

        result = self.expense_model.objects.filter(
            user=request.user,
            date__month=this_month,
            date__year=this_year
        )\
        .values('category__name', 'category__hex_color')\
        .annotate(total_amount=Sum('amount'))\
        .order_by('total_amount')

        labels = []
        expenses = []
        hex_colors = []

        if result:
            for category in result:
                amount_sum += category['total_amount']
                labels.append(category['category__name'])
                expenses.append(category['total_amount'])
                hex_colors.append(category['category__hex_color'])

        expense_data = {'labels': labels, 'data': expenses, 'hex_colors': hex_colors}

        data = {
            'amount_sum': amount_sum,
            'expense_data_json': json.dumps(expense_data)
        }
        return render(request, self.template_name, data)


class ExpenseCategoryView(LoggedInView):
    template_name = "main/expense_category.html"
    form_class = ExpenseForm
    expense_model = Expense
    category_model = ExpenseCategory

    def post(self, request, *args, **kwargs):
        submit_val = request.POST.get('submit')

        category = self.category_model.objects.get(slug=self.kwargs['slug'])

        if submit_val == 'add':
            form = self.form_class(request.POST)
            if form.is_valid():
                obj = form.save(commit=False)
                obj.user = request.user
                obj.category = category
                obj.save()
                messages.success(request, 'Expense added')
            else:
                messages.error(request, f'Expense add failed{form.errors}')

        if submit_val == 'delete':
            obj_pk = request.POST.get('delete_pk')
            try:
                obj = self.expense_model.objects.get(
                    user=request.user,
                    pk=obj_pk
                )
            except ObjectDoesNotExist:
                messages.error(request, 'Expense delete failed')
            else:
                obj.delete()
                messages.success(request, 'Expense deleted')

        if submit_val == 'edit':
            try:
                check_obj = self.expense_model.objects.get(
                    user=request.user,
                    pk=request.POST.get('edit_pk')
                )
                form = self.form_class(request.POST, instance=check_obj)
            except ObjectDoesNotExist:
                messages.error(request, 'Expense update failed')
            else:
                if form.is_valid():
                    obj = form.save(commit=False)
                    obj.user = request.user
                    obj.category = category
                    obj.save()
                    messages.success(request, 'Expense updated')
                else:
                    messages.error(request, f'Expense update failed{form.errors}')

        return HttpResponseRedirect(self.request.path_info)

    def get(self, request, *args, **kwargs):

        category = get_object_or_404(
            self.category_model,
            slug__iexact=self.kwargs['slug']
        )

        this_month = datetime.now().month
        this_year = datetime.now().year
        user_expense_data = self.expense_model.objects.filter(
            user=request.user,
            date__month=this_month,
            date__year=this_year,
            category=category
        )
        data = {
            'user_data': user_expense_data,
            'expense_form_edit': self.form_class(),
            'expense_form_add': self.form_class(),
            'amount_sum': user_expense_data.aggregate(Sum('amount'))['amount__sum'],
            'category_name': category.name,
            'category_description': category.long_description
        }
        return render(request, self.template_name, data)

main/templates/main/account.html
{% extends 'members_base.html' %}
{% load static %}
{% block title %}Account & Settings{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <h4>Account & Settings</h4>
    </div>
</div>

<div class="row mt-3">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h6 class="card-title">Change your email address</h6>
      </div>
      <div class="card-body">
        <p class="card-text">Your email address is currently set to: {{user_email}}</p>
        <form class="row g-3" method="post">
          {% csrf_token %}
          <div class="col-auto">
            <input type="email" name="new_email" class="form-control" id="changeemail" placeholder="New email address" required>
          </div>
          <div class="col-auto">
            <button type="submit" class="btn btn-primary mb-3" name="submit" value="changeemail">Change Email Address</button>
          </div>
      </form>
      </div>
    </div>
  </div>
</div>

<div class="row mt-3">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h6 class="card-title">Delete your account</h6>
      </div>
      <div class="card-body">
        <p class="card-text">Click the button below to delete your account. All of your user data will be removed.</p>
        <button type="button" data-bs-toggle="modal" data-bs-target="#deleteaccountmodal" class="btn btn-danger deleteaccount-button btn-sm">Delete Account</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteaccountmodal" tabindex="-1" aria-labelledby="deleteaccountmodallabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Delete Account</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="modal-body">
                <p>Are you sure you want to delete your account? All data for your user will be permanently deleted and cannot be recovered.</p>
                <p>This cannot be undone!</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger" name="submit" value="deleteaccount">Confirm Delete Account</button>
            </div>
        </form>
      </div>
    </div>
</div>

{% endblock %}

main/templates/main/dashboard.html
{% extends 'members_base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock %}

{% block content %}
<p>Hi {{ user.username }}!</p>
<p>Total expenses for the current month: {{amount_sum}}</p>
{% if amount_sum > 0 %}
<div class="row">
    <div class="col-md-4">
        <canvas id="myChart" width="400" height="400"></canvas>
    </div>
    <div class="col-md-4"></div>
    <div class="col-md-4"></div>
</div>
{% else %}
<p>If your expenses were greater than 0, you'd see some pretty graphs here!</p>
{% endif %}
<script type="text/javascript">
    const ctx = document.getElementById('myChart').getContext('2d');
    const labels = JSON.parse('{{expense_data_json|safe}}').labels
    const expensedata = JSON.parse('{{expense_data_json|safe}}').data
    const colors = JSON.parse('{{expense_data_json|safe}}').hex_colors
    const data = {
        labels: labels,
        datasets: [{
        data: expensedata,
        hoverOffset: 4,
        backgroundColor: colors,
        }]
    };
    const myChart = new Chart(ctx, {
        type: 'doughnut',
        data: data,
        options: {
            maintainAspectRatio: false,
            plugins: {
                title: {
                    display: true,
                    text: 'Expense category totals for the current month',
                    font: {
                        size: 18
                    }
                }
        }
        }
    });
</script>
{% endblock %}

main/templates/main/expense_category.html
{% extends 'members_base.html' %}
{% load my_filters %}
{% block title %}{{category_name}}{% endblock %}

{% block content %}

<script type="text/javascript">
  $(document).ready(function (){
    $('.delete-button').click(function(){
        var pk = $(this).data("pk");
        var description = $(this).data("description");
        $("#deletemodal .description").text(description);
        $('#deletemodal #delete-pk').attr('value', pk);
    });

    $('.edit-button').click(function(){
        var pk = $(this).data("pk");
        var description = $(this).data("description");
        var amount = $(this).data("amount");
        $('#editmodal #edit-pk').attr('value', pk);
        $('#editmodal #id_description').attr('value', description);
        $('#editmodal #id_amount').attr('value', amount);
    });
  })
</script>

<h4>{{category_name}}</h4>

<p>{{category_description}}<br>Keep track of your {{category_name|lower}} expenses here.</p>

<h5>Current month {{category_name|lower}} expenses:</h5>

<table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">Amount</th>
        <th scope="col">Description</th>
        <th scope="col">Date Added</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
        {% for expense in user_data.all %}
        <tr>
            <td>{{expense.amount}}</td>
            <td>{{expense.description}}</td>
            <td>{{expense.date}}</td>
            <td>
              <button type="button" data-bs-toggle="modal" data-bs-target="#editmodal" class="btn btn-primary edit-button btn-sm" data-pk="{{expense.pk}}" data-description="{{expense.description}}" data-amount="{{expense.amount}}">Edit</button>
              <button type="button" data-bs-toggle="modal" data-bs-target="#deletemodal" class="btn btn-danger delete-button btn-sm" data-pk="{{expense.pk}}" data-description="{{expense.description}}">Delete</button>
            </td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="4">Total: {% if amount_sum %}{{amount_sum}}{% else %}0{% endif %}</td>
        </tr>
    </tbody>
</table>

<h5>Add new {{category_name|lower}} expense:</h5>

<form class="row g-3" method="post">
    {% csrf_token %}
    {% for field in expense_form_add %}
    <div class="col-auto">
      <label for="{{ field.id_for_label }}" class="visually-hidden">{{ field.label_tag }}</label>
      <input type="text" name="{{ field.name }}" class="form-control" id="{{ field.id_for_label }}" placeholder="{{ field.name }}" required>
    </div>
    {% endfor %}
    <div class="col-auto">
      <button type="submit" class="btn btn-primary mb-3" name="submit" value="add">Add Expense</button>
    </div>
</form>


<!-- Modal -->
<div class="modal fade" id="deletemodal" tabindex="-1" aria-labelledby="deletemodallabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Delete Expense Item</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="modal-body">
                Delete expense item <span class="description"></span>?
            </div>
            <div class="modal-footer">
                <input type="hidden" id="delete-pk" name="delete_pk" value="">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger" name="submit" value="delete">Confirm Delete</button>
            </div>
        </form>
      </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="editmodal" tabindex="-1" aria-labelledby="editmodallabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Edit Expense Item</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form method="post">
          {% csrf_token %}
          <div class="modal-body">
            {% for field in expense_form_edit %}
            <div class="mb-3">
              <label for="{{ field.id_for_label }}" class="form-label">{{ field.label_tag }}</label>
              <input type="text" name="{{ field.name }}" class="form-control" id="{{ field.id_for_label }}" value="">
            </div>
            {% endfor %}
          </div>
          <div class="modal-footer">
              <input type="hidden" id="edit-pk" name="edit_pk" value="">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary" name="submit" value="edit">Submit</button>
          </div>
      </form>
    </div>
  </div>
</div>
  
{% endblock %}

main/templates/main/login.html
{% extends 'auth_base.html' %}

{% block title %}Login{% endblock %}

{% load my_filters %}

{% block content %}

<div class="row mt-5">
  {% if messages %}
  <div class="text-center mb-2">
  {% for message in messages %}
    {{ message|safe }}
  {% endfor %}
  </div>
  {% endif %}
  <div class="card mx-auto" style="width: 24rem;">
    <div class="card-body">
      <h5 class="card-title">Log In</h5>
      <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="mb-3">
          <label for="{{ field.id_for_label }}" class="form-label">{{ field.label_tag }}</label>
          <input name="{{ field.name }}" type="{{field.widget_type}}" class="form-control" id="{{ field.id_for_label }}">
        </div>
        {% endfor %}
        <div class="mb-3">
          <a href="">Forgot password?</a>
        </div>
        <button type="submit" class="btn btn-primary">Log In</button>
      </form>
      <p class="mt-3">Don't have an account? Sign up <a href="{% url 'signup' %}">here</a>.</p>
    </div>
  </div>
</div>

{% endblock %}

main/templates/main/signup.html
{% extends "auth_base.html" %}

{% block title %}Sign Up{% endblock %}

{% load my_filters %}

{% block content %}

<script type="text/javascript">
  $(document).ready(function (){
    $("[data-bs-toggle=tooltip]").tooltip()
  })
</script>
<style> 
  .tooltip-inner {
    text-align: left!important;
}
</style>
 
<div class="row mt-5">

  {% if messages %}
  <div class="text-center mb-2">
  {% for message in messages %}
    {{ message|safe }}
  {% endfor %}
  </div>
  {% endif %}

  {% if form.errors %}
    <div class="text-center mb-2">
      {% for field in form %}
        {% for error in field.errors %}
          <div><i class="bi bi-x-circle-fill"></i> {{error}}</div>
        {% endfor %}
      {% endfor %}
    </div>
  {% endif %}

  <div class="card mx-auto" style="width: 24rem;">
    <div class="card-body">
      <h5 class="card-title">Sign up</h5>
      <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="mb-3">
          <label for="{{ field.id_for_label }}" class="form-label">{{ field.label_tag }} <a href="#" data-bs-toggle="tooltip" data-bs-html="true" data-bs-placement="right" data-bs-title="{{field.help_text}}"><i class="bi bi-question-circle-fill"></i></a></label>
          <input name="{{ field.name }}" type="{{field.widget_type}}" class="form-control" id="{{ field.id_for_label }}">
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Sign Up</button>
      </form>
      <p class="mt-3">Already have an account? Sign in <a href="{% url 'login' %}">here</a>.</p>
    </div>
  </div>
</div>

{% endblock %}

main/templates/main/support.html
{% extends 'members_base.html' %}
{% load static %}
{% load my_filters %}
{% block title %}Support{% endblock %}

{% block content %}
<div class="row">
    <h4>Support</h4>
    <p>Do you need help, want to report a bug, or make a suggestion on how we can improve the service? Fill out the support ticket form below and we'll reply as soon as possible!</p>
</div>

<div class="row mt-3">
    <h5>New Support Ticket</h5>
    <div class="col-md-4">
        <form method="post">
            {% csrf_token %}
            {% for field in new_ticket_form %}
            <div class="mb-3">
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label_tag }}</label>
                {% if field.widget_type == 'textarea' %}
                <textarea name="{{ field.name }}" class="form-control" id="{{ field.id_for_label }}" rows="5"></textarea>
                {% else %}
                <input name="{{ field.name }}" type="{{field.widget_type}}" class="form-control" id="{{ field.id_for_label }}">
                {% endif %}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

<div class="row mt-5">
    <h5>Your Support Tickets</h5>
    {% if user_tickets %}
    <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">Status</th>
            <th scope="col">Subject</th>
            <th scope="col">Date</th>
          </tr>
        </thead>
        <tbody>
            {% for ticket in user_tickets.all %}
            <tr>
                <td>{{ticket.status}}</td>
                <td><a href="{% url 'ticket' pk=ticket.pk %}">{{ticket.subject}}</a></td>
                <td>{{ticket.date}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>You don't currently have any support tickets.</p>
    {% endif %}
</div>

{% endblock %}

main/templates/main/ticket.html
{% extends 'members_base.html' %}
{% load static %}
{% block title %}Ticket #{{object.pk}}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <h4>Ticket #{{object.pk}}</h4>
        <h5>Subject: {{object.subject}}</h5>
        <p>Date: {{object.date}}<br>Status: {{object.status}}</p>
        <p>{{object.body}}</p>
    </div>
</div>

<div class="row mt-4">
    <div class="col-md-6">
        <h5>Replies</h5>
        {% if object.replies.all %}
        {% for reply in object.replies.all %}
            <div class="ps-3 pt-2 mt-2 {% if reply.user.is_staff %}staff-ticket-reply{% else %}user-ticket-reply{% endif %}">
                <p>From: {{reply.user}}<br>Reply Date: {{reply.date}}</p>
                <p>{{reply.body}}</p>
            </div>
        {% endfor %}
        {% else %}
        <p>No replies.</p>
        {% endif %}
    </div>
</div>

<div class="row mt-5 mb-5">
    <div class="col-md-4">
        <h5>Add new reply</h5>
        {% if object.status == 'Closed' %}
        <p>Ticket is closed.</p>
        {% else %}
        <form method="post">
            {% csrf_token %}
            {% for field in ticket_reply_form %}
            <div class="mb-3">
                {% if field.widget_type == 'textarea' %}
                <textarea name="{{ field.name }}" class="form-control" id="{{ field.id_for_label }}" rows="5"></textarea>
                {% else %}
                <input name="{{ field.name }}" type="{{field.widget_type}}" class="form-control" id="{{ field.id_for_label }}">
                {% endif %}
            </div>
            {% endfor %}
            <div class="form-check">
                <input class="form-check-input" name="close_ticket" type="checkbox" id="close-ticket">
                <label class="form-check-label" for="close-ticket">
                    Close ticket?
                </label>
              </div>
            <button type="submit" class="btn btn-primary mt-3">Submit</button>
        </form>
        {% endif %}
    </div>
</div>

{% endblock %}